### ISSUE TITLE
Should throw error when unknown permission is requested

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-snaps-beta#27]
Like a method not found error, maybe? Or do we want to support partial-resolutions? Might be nice to fail-hard by default, but allow a dapp to provide a parameter specifying that it's okay if a feature isn't supported, just leave it out?

Currently we display any unknown permissions to the user, and that's bad, b/c they could approve something that _eventually_ becomes a permission.

**Comment by rekmarks** [comment]
I'm not sure if the "unknown permissions" are plugin-specific or dapp-specific. Please see the following PR: https://github.com/MetaMask/metamask-plugin-beta/pull/87
