### ISSUE TITLE
Performance issue: setTimeout handlers

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-snaps-beta#31]
It seems that the performance hit we've noticed on this branch is related to Sentry.

To see for yourself:
- Open the background console
- Select "Verbose" logging.

<img width="866" alt="Screen Shot 2019-09-29 at 3 20 13 PM" src="https://user-images.githubusercontent.com/542863/65840335-b0dd2700-e2cc-11e9-9f4d-3726d72b796b.png">

Notice that there are lots of these messages:
```
[Violation] 'setTimeout' handler took 167ms
index.js:3205 [Violation] 'setTimeout' handler took 179ms
index.js:3205 [Violation] 'setTimeout' handler took 164ms
index.js:3205 [Violation] 'setTimeout' handler took 170ms
index.js:3205 [Violation] 'setTimeout' handler took 219ms
index.js:3205 [Violation] 'setTimeout' handler took 171ms
index.js:3205 [Violation] 'setTimeout' handler took 165ms
index.js:3205 [Violation] 'setTimeout' handler took 212ms
```

**Comment by Gudahtt** [comment]
I'm not sure I follow how this relates to Sentry; are those warning line numbers within Sentry code?
I suspect those warnings are issued by Chrome (e.g. https://stackoverflow.com/questions/41218507/violation-long-running-javascript-task-took-xx-ms)

**Comment by jennypollack** [comment]
#37 disabled sentry, so title is misleading, changed

**Comment by rekmarks** [comment]
This issue seems particular to this repo, and we therefore won't fix it.
